config/routes.rb
Rails.application.routes.draw do
  resources "entries"
  resources "places"
  resources "sessions"
  resources "users"

  get("/login", { controller: "sessions", action: "new" })
  post("/login", { controller: "sessions", action: "create" })
  get("/logout", { controller: "sessions", action: "destroy" })
  get("/signup", { controller: "users", action: "new" })
  get("/", { controller: "places", action: "index" })
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord

  has_one_attached :uploaded_image  
  
end

app/models/place.rb
class Place < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user

  def current_user
    puts "------------------ code before every request ------------------"
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  
  def index
    if session["user_id"] 
      @entries = Entry.where(user_id: session["user_id"])  
    else
      redirect_to "/login", notice: "You must be logged in to view your entries."  
    end
  end

  
  
  
  
  def new
  end

  def create
    if session["user_id"] 
      @entry = Entry.new
      @entry["title"] = params["title"]
      @entry["description"] = params["description"]
      @entry["occurred_on"] = params["occurred_on"]
      @entry["place_id"] = params["place_id"]
      @entry["user_id"] = session["user_id"] 

      @entry.uploaded_image.attach(params["uploaded_image"])


      if @entry.save
        redirect_to "/places/#{@entry["place_id"]}", notice: "Entry created successfully!"
      else
        redirect_to "/entries/new", notice: "Failed to create entry."
      end
    else
      redirect_to "/login", notice: "You must be logged in to create an entry."
    end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @places = Place.all
  end

  def show
    @place = Place.find_by({ "id" => params["id"] })
    @entries = Entry.where({ "place_id" => @place["id"], "user_id" => session["user_id"]})
  end

  def new
  end

  def create
    @place = Place.new
    @place["name"] = params["name"]
    @place.save
    redirect_to "/places"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by({ "email" => params["email"] })
    if @user != nil
      if BCrypt::Password.new(@user["password"]) == params["password"]
        session["user_id"] = @user["id"]
        flash["notice"] = "Welcome."
        redirect_to "/places"
      else
        flash["notice"] = "Nope."
        redirect_to "/login"
      end
    else
      flash["notice"] = "Nope."
      redirect_to "/login"
    end
  end

  def destroy
    session["user_id"] = nil
    flash["notice"] = "Goodbye."
    redirect_to "/login"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    if User.find_by({ "email" => params["email"] }) == nil
      @user = User.new
      @user["username"] = params["username"]
      @user["email"] = params["email"]
      @user["password"] = BCrypt::Password.create(params["password"])
      @user.save
      redirect_to "/login"
    else
      flash["notice"] = "Email taken."
      redirect_to "/users/new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/index.html.erb
<h1>Entries</h1>

<ul>
  <% if @entries.any? %>
    <% @entries.each do |entry| %>
      <li>
        <a href="/entries/<%= entry.id %>"><%= entry.title %></a>

        <% if entry.uploaded_image.attached? %>
          <br>
          <img src="<%= url_for(entry.uploaded_image) %>" class="img-fluid" style="max-width: 200px;">
        <% else %>
          <p class="text-muted">No image uploaded.</p>
        <% end %>

      </li>
    <% end %>
  <% else %>
    <li class="text-muted">No entries yet</li>
  <% end %>
</ul>

<div class="text-center mt-3 mb-4"> 
  <%= link_to "New Entry", new_entry_path, class: "btn btn-outline-dark" %>
</div>

app/views/entries/new.html.erb
<h1>New Entry</h1>
<%# Only display form when user is logged in. %>
<% if User.find_by({ "id" => session["user_id"] }) != nil %>

<form action="/entries" method="post" enctype="multipart/form-data">

<div class="mb-3">
  <label for="uploaded_image_input" class="form-label">Upload Image</label>
  <input type="file" name="uploaded_image" id="uploaded_image_input" class="form-control" accept="image/png, image/jpg, image/jpeg, image/gif">
</div>



  <input type="hidden" name="place_id" value="<%= params["place_id"] %>">
  <p>
    <label for="title_input">Title</label>
    <input type="text" name="title" id="title_input">
  </p>
  <p>
    <label for="description_input">Description</label>
    <input type="text" name="description" id="description_input">
  </p>
  <p>
    <label for="occurred_on_input">Occurred On</label>
    <input type="date" name="occurred_on" id="occurred_on_input">
  </p>
  <button>Save</button>
</form>
<% else %>
  <p>
    You must be <a href="/login">logged in</a>.
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tacostagram Final</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/stylesheets/application.css">
  </head>

  <body>

    <div class="container mt-3">
      <% if flash[:notice] %>
        <div class="alert alert-success"><%= flash[:notice] %></div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger"><%= flash[:alert] %></div>
      <% end %>
    </div>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container">
        <a class="navbar-brand" href="#">Tacostagram</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" 
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
                <%= link_to "Home", "/", class: "nav-link active", "aria-current": "page" %>
            </li>
            <% if session[:user_id] %>
              <li class="nav-item">
                <%= link_to "Logout", "/logout", method: :delete, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Login", login_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Signup", signup_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container mt-4">
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/places/index.html.erb
<h1>Places</h1>

<ul>
  <% for place in @places %>
    <li><a href="/places/<%= place["id"] %>"><%= place["name"] %></a></li>
  <% end %>
</ul>

<p>
   <%= link_to "New Place", new_place_path, class: "btn btn-outline-dark" %>
</p>

app/views/places/new.html.erb
<h1>New Place</h1>

<form action="/places" method="post">
  <p>
    <label for="name_input">Name</label>
    <input type="text" name="name" id="name_input">
  </p>

  <button>Save</button>
</form>

app/views/places/show.html.erb
<h1><%= @place["name"] %></h1>

<h2>My Entries</h2>
<% for entry in @entries %>
  <h3><%= entry["title"] %></h3>
  <h4><%= entry["occurred_on"] %></h4>
  <p><%= entry["description"] %></p>
<% if entry.uploaded_image.attached? %>
  <img src="<%= url_for(entry.uploaded_image) %>" class="img-fluid">
<% else %>
  <img src="<%= entry["image"] %>" class="img-fluid">
<% end %>
<% end %>

<p>
  <a href="/entries/new?place_id=<%= @place["id"] %>">New Entry</a>
</p>

<p>
  <a href="/places">Back to All Places</a>
</p>

app/views/users/new.html.erb
<h1>New User Account</h1>

<form action="/users" method="post">
  <p>
    <label for="username">Username</label>
    <input type="text" name="username" id="username">
  </p>
  <p>
    <label for="email">Email</label>
    <input type="text" name="email" id="email">
  </p>
  <p>
    <label for="password">Password</label>
    <input type="password" name="password" id="password">
  </p>
  <button>Signup</button>
</form>